# CelsTrak (https://celestrak.com/NORAD/elements/)
satellite_source_data = {
  # Special-Interest
  'last_30_days': 'https://celestrak.com/NORAD/elements/tle-new.txt',
  'space_stations': 'https://www.celestrak.com/NORAD/elements/stations.txt',
  'brightest_100_satellites': 'https://www.celestrak.com/NORAD/elements/visual.txt',
  'active_satellites': 'https://www.celestrak.com/NORAD/elements/active.txt',
  # Weather & Earth Resources
  'weather_satellites': 'https://celestrak.com/NORAD/elements/weather.txt',
  'noaa': 'https://celestrak.com/NORAD/elements/noaa.txt',
  'goes': 'https://celestrak.com/NORAD/elements/goes.txt',
  'earth_resources': 'https://celestrak.com/NORAD/elements/resource.txt',
  'search_and_rescue': 'https://celestrak.com/NORAD/elements/sarsat.txt',
  'disaster_monitoring': 'https://celestrak.com/NORAD/elements/dmc.txt',
  'TDRSS': 'https://celestrak.com/NORAD/elements/tdrss.txt',
  'ARGOS': 'https://celestrak.com/NORAD/elements/argos.txt',
  'planet': 'https://celestrak.com/NORAD/elements/planet.txt',
  'spire': 'https://celestrak.com/NORAD/elements/spire.txt',
  # Communications
  'geosynchronous': 'https://celestrak.com/NORAD/elements/geo.txt',
  #'geo_protected_zone': 'https://celestrak.com/satcat/gpz.php'
  #'geo_protected_zone_plus': 'https://celestrak.com/satcat/gpz-plus.php',
  'intelsat': 'https://celestrak.com/NORAD/elements/intelsat.txt',
  'ses': 'https://celestrak.com/NORAD/elements/ses.txt',
  'iridium': 'https://celestrak.com/NORAD/elements/iridium.txt',
  'iridium_next': 'https://celestrak.com/NORAD/elements/iridium-NEXT.txt',
  'starlink': 'https://celestrak.com/NORAD/elements/starlink.txt',
  'orbcomm': 'https://celestrak.com/NORAD/elements/orbcomm.txt',
  'globalstar': 'https://celestrak.com/NORAD/elements/globalstar.txt',
  'amateur_radio': 'https://celestrak.com/NORAD/elements/amateur.txt',
  'experimental': 'https://celestrak.com/NORAD/elements/x-comm.txt',
  'other_commuication': 'https://celestrak.com/NORAD/elements/other-comm.txt',
  'satnogs': 'https://celestrak.com/NORAD/elements/satnogs.txt',
  'gorizont': 'https://celestrak.com/NORAD/elements/gorizont.txt',
  'raduga': 'https://celestrak.com/NORAD/elements/raduga.txt',
  'molniya': 'https://celestrak.com/NORAD/elements/molniya.txt',
  # Navigation
  'gps_operational': 'https://celestrak.com/NORAD/elements/gps-ops.txt',
  'glonass_operational': 'https://celestrak.com/NORAD/elements/glo-ops.txt',
  'galileo': 'https://celestrak.com/NORAD/elements/galileo.txt',
  'beidou': 'https://celestrak.com/NORAD/elements/beidou.txt',
  'sbas': 'https://celestrak.com/NORAD/elements/sbas.txt',
  'nnss': 'https://celestrak.com/NORAD/elements/nnss.txt',
  'russian_leo_navigation': 'https://celestrak.com/NORAD/elements/musson.txt',
  # Scientific
  'space_and_earth_science': 'https://celestrak.com/NORAD/elements/science.txt',
  'geodetic': 'https://celestrak.com/NORAD/elements/geodetic.txt',
  'engineering': 'https://celestrak.com/NORAD/elements/engineering.txt',
  'education': 'https://celestrak.com/NORAD/elements/education.txt',
  # Misc
  'misc_military': 'https://celestrak.com/NORAD/elements/military.txt',
  'radar_calibration': 'https://celestrak.com/NORAD/elements/radar.txt',
  'cubesat': 'https://celestrak.com/NORAD/elements/cubesat.txt',
  'misc': 'https://celestrak.com/NORAD/elements/other.txt'
}

# Space-Track.org (https://www.space-track.org/#catalog)
spacetrack_identity = 'download_shit@outlook.com'
spacetrack_password = 'JZwmt8IvaQdMNgxlH7EV'
spacetack_url = 'https://www.space-track.org/ajaxauth/login'

# n2yo.com (https://www.n2yo.com/satellites/)
categories = {
  'amateur_radio': 'https://www.n2yo.com/satellites/?c=18',
  'beidou_navigation_system': 'https://www.n2yo.com/satellites/?c=35',
  'brightest': 'https://www.n2yo.com/satellites/?c=1',
  'celestis': 'https://www.n2yo.com/satellites/?c=45',
  'cubeSats': 'https://www.n2yo.com/satellites/?c=32',
  'disaster_monitoring': 'https://www.n2yo.com/satellites/?c=8',
  'earth_resources': 'https://www.n2yo.com/satellites/?c=6',
  'education': 'https://www.n2yo.com/satellites/?c=29',
  'engineering': 'https://www.n2yo.com/satellites/?c=28',
  'experimental': 'https://www.n2yo.com/satellites/?c=19',
  'flock': 'https://www.n2yo.com/satellites/?c=48',
  'GOES': 'https://www.n2yo.com/satellites/?c=5',
  'galileo': 'https://www.n2yo.com/satellites/?c=22',
  'geodetic': 'https://www.n2yo.com/satellites/?c=27',
  'geostationary': 'https://www.n2yo.com/satellites/?c=10',
  'gps_constellation': 'https://www.n2yo.com/satellites/?c=50',
  'gps_operational': 'https://www.n2yo.com/satellites/?c=20',
  'globalstar': 'https://www.n2yo.com/satellites/?c=17',
  'glonass_constellation': 'https://www.n2yo.com/satellites/?c=51',
  'glonass_operational': 'https://www.n2yo.com/satellites/?c=21',
  'gonets': 'https://www.n2yo.com/satellites/?c=40',
  'gorizont': 'https://www.n2yo.com/satellites/?c=12',
  'IRNSS': 'https://www.n2yo.com/satellites/?c=46',
  'ISS': 'https://www.n2yo.com/satellites/?c=2',
  'intelsat': 'https://www.n2yo.com/satellites/?c=11',
  'iridium': 'https://www.n2yo.com/satellites/?c=15',
  'lemur': 'https://www.n2yo.com/satellites/?c=49',
  'military': 'https://www.n2yo.com/satellites/?c=30',
  'molniya': 'https://www.n2yo.com/satellites/?c=14',
  'NOAA': 'https://www.n2yo.com/satellites/?c=4',
  'navy_navigation_satellite_system': 'https://www.n2yo.com/satellites/?c=24',
  'o3b_networks': 'https://www.n2yo.com/satellites/?c=43',
  'orbcomm': 'https://www.n2yo.com/satellites/?c=16',
  'parus': 'https://www.n2yo.com/satellites/?c=38',
  'QZSS': 'https://www.n2yo.com/satellites/?c=47',
  'radar_calibration': 'https://www.n2yo.com/satellites/?c=31',
  'raduga': 'https://www.n2yo.com/satellites/?c=13',
  'russian_leo_navigation': 'https://www.n2yo.com/satellites/?c=25',
  'satellite_based_augmentation_system': 'https://www.n2yo.com/satellites/?c=23',
  'search_and_rescue': 'https://www.n2yo.com/satellites/?c=7',
  'space_and_earth_science': 'https://www.n2yo.com/satellites/?c=26',
  'starlink': 'https://www.n2yo.com/satellites/?c=52',
  'strela': 'https://www.n2yo.com/satellites/?c=39',
  'TV': 'https://www.n2yo.com/satellites/?c=34',
  'tracking_and_data_relay_satellite_system': 'https://www.n2yo.com/satellites/?c=9',
  'tselina': 'https://www.n2yo.com/satellites/?c=44',
  'tsikada': 'https://www.n2yo.com/satellites/?c=42',
  'tsiklon': 'https://www.n2yo.com/satellites/?c=41',
  'weather': 'https://www.n2yo.com/satellites/?c=3',
  'westford_needles': 'https://www.n2yo.com/satellites/?c=37',
  'xm_and_sirius': 'https://www.n2yo.com/satellites/?c=33',
  'yaogan': 'https://www.n2yo.com/satellites/?c=36'
}