version: '3'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    command: npm run serve
    volumes:
      - ./client:/app
      - /app/node_modules/
    ports:
      - "8080:8080"
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./server/api/Dockerfile
    command: node app.js
    volumes:
      - ./server/api:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    links:
     - redis
     - postgres
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: "postgres:latest"
    volumes:
    - ./db/postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: uphere-space
      POSTGRES_USER: uphere-admin
      POSTGRES_PASSWORD: c87PGaqOxDR8pdXz15zO
  tracking:
    container_name: python
    image: "python:latest"
    build:
      context: .
      dockerfile: ./server/tracking/Dockerfile
    command: python3 /tracking/populate_tle.py
    depends_on:
      - redis
    volumes:
      - ./server/tracking:/tracking
    links:
     - redis