version: '3'
services:
  api:
    container_name: api
    build: .
    command: node app.js
    volumes:
      - ./server/api:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    links:
     - redis
     - postgres
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      POSTGRES_USER: uphere-admin
      POSTGRES_DB: uphere-space
  tracking:
    container_name: python
    image: "python:latest"
    build:
      context: .
      dockerfile: ./server/tracking/Dockerfile
    command: python3 /tracking/populate_tle.py
    depends_on:
      - redis
    volumes:
      - ./server/tracking:/tracking
    links:
     - redis