import { library } from "@fortawesome/fontawesome-svg-core";

// Solid icons
import {
  faAngleDoubleDown,
  faAngleDoubleUp,
  faBook,
  faBroadcastTower,
  faCalendarAlt,
  faCaretDown,
  faCaretRight,
  faCloudShowersHeavy,
  faCog,
  faCube,
  faExternalLinkAlt,
  faFighterJet,
  faFilter,
  faFireAlt,
  faFirstAid,
  faFlask,
  faGlobeAmericas,
  faHouseDamage,
  faImages,
  faInfoCircle,
  faLayerGroup,
  faLocationArrow,
  faMapMarkerAlt,
  faMeteor,
  faPhoneSquare,
  faQuestionCircle,
  faRocket,
  faSatellite,
  faSatelliteDish,
  faSearch,
  faSkull,
  faSlidersH,
  faSortAlphaDown,
  faSortAlphaUp,
  faStar,
  faTimes,
  faToggleOn,
  faToggleOff,
  faTv,
  faVideo
} from "@fortawesome/free-solid-svg-icons";

// Brand icons
import { faFacebook, faTwitter } from "@fortawesome/free-brands-svg-icons";

export default [
  library.add(
    faAngleDoubleDown,
    faAngleDoubleUp,
    faBook,
    faBroadcastTower,
    faCalendarAlt,
    faCaretDown,
    faCaretRight,
    faCloudShowersHeavy,
    faCog,
    faCube,
    faExternalLinkAlt,
    faFacebook,
    faFighterJet,
    faFilter,
    faFireAlt,
    faFirstAid,
    faFlask,
    faGlobeAmericas,
    faHouseDamage,
    faImages,
    faInfoCircle,
    faLayerGroup,
    faLocationArrow,
    faMapMarkerAlt,
    faMeteor,
    faPhoneSquare,
    faQuestionCircle,
    faRocket,
    faSatellite,
    faSatelliteDish,
    faSearch,
    faSkull,
    faSlidersH,
    faSortAlphaDown,
    faSortAlphaUp,
    faStar,
    faTimes,
    faToggleOn,
    faToggleOff,
    faTv,
    faTwitter,
    faVideo
  )
];
